### ISSUE TITLE
inference on cuda.

### ISSUE THREAD

**Issue by MyraBaba** [jankolf/ser-fiq-pytorch#2]
@jankolf 
how to make inference on the Gpu ? 

changing device to cuda gives error..

also i changed to resnet50 it gives error. do I need extra code for resnet50 ? which one is better and %xdifference? 

device=cuda :error:

.py 
Traceback (most recent call last):
  File "/data/OpenSource/ser-fiq-pytorch/main.py", line 37, in <module>
    scores = resnet.calculate_serfiq(image, T=10, scaling=5.0)
  File "/data/OpenSource/ser-fiq-pytorch/venvSERFIQ/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/OpenSource/ser-fiq-pytorch/backbones/iresnet.py", line 194, in calculate_serfiq
    x = self.conv1(x)
  File "/data/OpenSource/ser-fiq-pytorch/venvSERFIQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/OpenSource/ser-fiq-pytorch/venvSERFIQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/OpenSource/ser-fiq-pytorch/venvSERFIQ/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/OpenSource/ser-fiq-pytorch/venvSERFIQ/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

**Comment by jankolf** [comment]
Hi,
you have to move the input also to the same gpu. Currently, your Input Type is torch.FloatTensor, which is a Tensor on the CPU.
The weights are on your GPU, thats why they are torch.**cuda**.FloatTensor.
To move the input also the GPU, use the .to(device) method:
```
torch_device = torch.device("cuda:0")
resnet = iresnet18(dropout=0.4,num_features=512, use_se=False).to(torch_device)
input = input.to(torch_device)
```

**Comment by MyraBaba** [comment]
How Imissed this :)

thanks...

I want ot test it my realtime face detector in c++..

Is there any onnx exported model do you mind to show me  ?

Best

**Comment by jankolf** [comment]
Hi,
currently, I have no exported model. You can try to follow [this tutorial from pytorch](https://pytorch.org/tutorials//beginner/onnx/export_simple_model_to_onnx_tutorial.html) to export it to onnx.
You will have to implement the prediction method again, I assume.
